name: Release and Publish to NPM

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout source code
          uses: actions/checkout@v4
          with:
            node-version: 18
            registry-url: "https://registry.npmjs.org"
            scope: "@nebulys"

        - name: Monorepo Install
          uses: ./.github/actions/yarn-nm-install
          with:
            cwd: "."
            enable-corepack: true
            cache-node-modules: true
            cache-install-state: true

        - name: Initialize the NPM config
          run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_AUTH: ${{ secrets.GH_TOKEN }}

        - name: Initialize Git User
          run: |
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor}}@users.noreply.github.com"

        - name: Run release
          run: yarn run release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}